### ISSUE TITLE
`P+3`: Ensure that the new and updated tests are traced to requirements 

### ISSUE THREAD

**Issue by Stenmarken** [KTH-DD2480-Fundsoft/pdm#18]
Relevant test cases (existing tests and updated/new tests related to the refactored code) are traced to
requirements.

**Comment by lskare** [comment]
Verkar redan som att Victor har löst detta i report.md under " Project plan for testing" ?

**Comment by Stenmarken** [comment]
Closing this issue since it has been merged to report
