### ISSUE TITLE
`T1`: Run regression tests and log results

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm#3]
Run the tests in main and store a log of the results. Investigate any failing tests and see if they interfere with our current issue.

**Comment by sebastianmonten** [comment]
The merge #21 resolves this issue. On branch `report` in folder `pdm/Fundsoft
/test_logs` there is a txt file with the printout of `pdm test` before we made any meaningful changes to our fork.
