### ISSUE TITLE
`T2`/`P4`: Identify and document requirements

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm#4]
From assignment description:

"Identify requirements related to the issue. If the requirements are not documented yet, try to de-
scribe them based on code reviews and existing test cases. Create a project plan for testing these
requirements, and working on the issue."
footnote:
"If you choose a task where the goal is to add, update, or refactor tests, add mechanisms that ensure that you have some kind of validation of the test behavior. This could include coverage, test output, or mutations detected by the tests."

DoD (Grading criteria): 
Requirements related to the functionality are identified and described in a systematic way. Each
requirement has a name (ID), title, and description. The description can be one paragraph per require-
ment.

**Comment by rasmus-d** [comment]
When using the `--allow-transitive` flag:
1. Passing a sub-dependency in lockfile should update the sub-dependency.
2. Passing a sub-dependency not in lockfile should throw an error.
3. Passing direct dependencies should update as usual
4. Passing a mix of direct and sub-dependencies should update the given dependencies
5. Updating a sub-dependency should not add it as a direct dependency.

Additionally, we should add completion for any arguments added to the CLI interface. 

--> report.md

**Comment by Stenmarken** [comment]
If we introduce the functionality of updating a sub-dependency to a specific version, then the 2nd requirement can be tested by trying to update to a version so that PDM cannot resolve the dependencies and then checking the lockfile hashes. That should be easier than trying to introduce circular dependencies.

**Comment by Stenmarken** [comment]
Closing this issue as the requirements are merged to the report branch.
