### ISSUE TITLE
`T3`: Create tests

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm#5]
From assignment description:
"Analyze existing test cases that relate to the issue. Do they contain good assertions? Do the assertions
cover the requirements as you understand them? If necessary, enhance existing regression tests with
properties derived from work done above, or write additional tests. Newly added tests related to
refactorings should pass, but if your task is a new feature, new tests should (initially) fail."

I.E. Create tests for how the new feature should work.

**Comment by Stenmarken** [comment]
Closing this as the tests has been merged into develop
