### ISSUE TITLE
`T4`: Ensure tests in #5 work

### ISSUE THREAD

**Issue by rasmus-d** [KTH-DD2480-Fundsoft/pdm#6]
From assignment description: 
"Make sure your new tests are actually executed. You can use code coverage measurement (especially
if this is available in the project you are using), or temporarily inject a fault (mutation) in the code,
and see that at least one test fails."

I.E. Review the tests in #5 and test them by checking coverage or mutating code.

**Comment by Stenmarken** [comment]
Since this code contains an injected error, it shouldn't be merged anywhere.
